### ISSUE TITLE
Increase tolerances for the leg/motor assemblies

### ISSUE THREAD

**Issue by matthieu-lapeyre** [poppy-project/poppy-humanoid#1]

**Comment by jgrizou** [comment]
Tolerance to change:
- tolerance on the side of motors.
- tolerance on the depth of the ollo head.
- tolerance on the diameter of the ollo holes.

**Comment by matthieu-lapeyre** [comment]
wrong repository ==> moved to https://github.com/poppy-project/Poppy-lightweight-biped-legs/issues/2
