### ISSUE TITLE
Update motor_naming_convention

### ISSUE THREAD

**Issue by show0k** [poppy-project/poppy-humanoid#16]
It will be usefull to update [motor_naming_convention.pdf](https://forum.poppy-project.org/t/assembly-instructions-motor-naming-convention-and-configuration/87) file with the new poppy hardware setup. A png file (with alpha layer) may be more appropriate than a pdf (which use jpeg compression).

**Comment by matthieu-lapeyre** [comment]
It is on the way
https://www.flickr.com/photos/poppy-project/21696451449/in/dateposted-public/

**Comment by show0k** [comment]
Any advance on that ?

**Comment by matthieu-lapeyre** [comment]
https://forum.poppy-project.org/t/versionning-et-documentation/1660/33?u=matthieu

**Comment by show0k** [comment]
![torso](https://cloud.githubusercontent.com/assets/3891499/10981573/d85a98f2-8408-11e5-9dc3-34c4fe7556ea.png)

**Comment by matthieu-lapeyre** [comment]
Tu n'en avais pas fait un pour l'Humanoid ? Je ne trouve plus la photo

[--- Commented from Asana.com
#commenter Théo Segonds
---[aa]
