### ISSUE TITLE
STL files not scaled for 3d printing

### ISSUE THREAD

**Issue by rjduran** [poppy-project/poppy-humanoid#2]
The mesh files are not scaled to the actual physical size when printed. I'm new to the project so I have not yet configured everything. Do the files get scaled somewhere in software? For example, the l_foot.stl file has the dimensions L = 0.05mm, W = 0.04mm, H = 0.15mm

**Comment by matthieu-lapeyre** [comment]
Yep it's my fault, I wrongly exported file into "meter" instead of "millimeter"...

I explained it here:https://forum.poppy-project.org/t/release-of-poppy-1-0-price-and-date/928/

I will try to re-export them ASAP.

**Comment by rjduran** [comment]
Got it. Thanks!

**Comment by matthieu-lapeyre** [comment]
I keep it open until I solve it. 

Thanks for raising it as an issue.

**Comment by matthieu-lapeyre** [comment]
New export available here: https://github.com/poppy-project/poppy-humanoid/releases/download/1.0-pre-release/STL_3D_printed_parts.zip

I also created a tutorial and a python script to simplify the STL export of 3D printed parts from Solidworks. See here: https://github.com/poppy-project/poppy-humanoid/tree/master/hardware/doc/Poppy_Humanoid_assembly_instructions.md
