### ISSUE TITLE
Release download is veeerryyy slow 

### ISSUE THREAD

**Issue by matthieu-lapeyre** [poppy-project/poppy-humanoid#27]
It takes ages to download the iso from the release.
<img width="842" alt="capture d ecran 2016-04-10 a 16 59 20" src="https://cloud.githubusercontent.com/assets/4503773/14411032/9dc1d8b2-ff3d-11e5-96f2-fe6db198bc56.png">

I do not have fiber connection yet 150 Kb/s is far from the max I can reach...

Maybe we should have a mirror with better performance ?

**Comment by pierre-rouanet** [comment]
On my side, no problem. I download at the maximum of my bandwidth capacities. 

Did you check https://status.github.com maybe they were just having some server issues?

**Comment by matthieu-lapeyre** [comment]
indeed, today it downloads at a normal speed.

**Comment by show0k** [comment]
Btw, releases are hosted on Amazon S3 ; I checked issues report and see nothing.
